version: 2.1

jobs:
  test:
    machine:
      enabled: true
    steps:
      - run: echo "Tests can run here!"
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Install Java & Maven
          command: ssh $SSH_USER@$SSH_HOST "sudo apt-get update && sudo apt-get install -y git openjdk-8-jdk maven"
      - run:
          name: Clear Repo
          command: ssh $SSH_USER@$SSH_HOST "rm -rf Fundamental_Project"
      - run:
          name: Pull repository
          command: ssh $SSH_USER@$SSH_HOST "git clone https://github.com/DKhan1998/Fundamental_Project.git"
      - run:
          name: Deploy Application
          command: ssh $SSH_USER@$SSH_HOST "cd ~/Fundamental_Project && mvn -Dmaven.test.skip=true spring-boot:run"
workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test
      - deploy: