version: 2.1

jobs:
  test:
    machine:
      enabled: true
    steps:
      - run: echo "Tests can run here!"
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Install Java & Maven
          command: ssh $SSH_USER@$SSH_HOST "sudo apt-get update && sudo apt-get install -y git && sudo apt-get install -y openjdk-8-jdk && mvn install -Dmaven.test.skip=true"
      - run:
          name: Pull repository
          command: ssh $SSH_USER@$SSH_HOST "cd ~/Fundamental_Project && git pull"
      - run:
          name: Deploy Application
          command: ssh $SSH_USER@$SSH_HOST "cd ~/Fundamental_Project &&  mvn clean package  && java -jar billyshakes-0.0.1-SNAPSHOT.jar"
workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test


